name: Vercel Protection Manager

on:
  workflow_dispatch:
    inputs:
      protection:
        description: 'Protection type (none, password, vercel)'
        required: true
        default: 'none'
        type: choice
        options:
          - none
          - password
          - vercel
      password:
        description: 'Protection password (if protection=password)'
        required: false
        type: string

jobs:
  manage-protection:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Configure Vercel Protection
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          echo "🔧 Configuration de la protection Vercel..."
          
          # Créer le fichier de configuration Vercel
          mkdir -p .vercel
          echo '{"orgId":"${{ secrets.VERCEL_ORG_ID }}","projectId":"${{ secrets.VERCEL_PROJECT_ID }}"}' > .vercel/project.json
          
          # Déterminer le type de protection
          PROTECTION_TYPE="${{ github.event.inputs.protection }}"
          
          if [ "$PROTECTION_TYPE" = "none" ]; then
            echo "📂 Désactivation de toute protection..."
            
            # Utiliser l'API Vercel pour désactiver la protection
            curl -X PATCH \
              "https://api.vercel.com/v9/projects/${{ secrets.VERCEL_PROJECT_ID }}" \
              -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d '{
                "passwordProtection": null,
                "ssoProtection": null,
                "trustedIps": null
              }'
              
            echo "✅ Protection désactivée"
            
          elif [ "$PROTECTION_TYPE" = "password" ]; then
            echo "🔒 Configuration de la protection par mot de passe..."
            
            # Configurer la protection par mot de passe
            curl -X PATCH \
              "https://api.vercel.com/v9/projects/${{ secrets.VERCEL_PROJECT_ID }}" \
              -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d '{
                "passwordProtection": {
                  "deploymentType": "all",
                  "password": "${{ github.event.inputs.password }}"
                }
              }'
              
            echo "✅ Protection par mot de passe configurée"
            
          elif [ "$PROTECTION_TYPE" = "vercel" ]; then
            echo "🔐 Configuration de Vercel Authentication..."
            
            # Note: Vercel Authentication nécessite des configurations au niveau du team
            echo "⚠️ Vercel Authentication doit être configuré dans le dashboard Vercel"
            echo "URL: https://vercel.com/${{ secrets.VERCEL_ORG_ID }}/${{ secrets.VERCEL_PROJECT_ID }}/settings/security"
          fi

      - name: Force Redeploy
        if: github.event.inputs.protection == 'none' || github.event.inputs.protection == 'password'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          echo "🚀 Redéploiement forcé..."
          
          # Déclencher un redéploiement
          vercel --prod --force --token="${{ secrets.VERCEL_TOKEN }}" --scope="${{ secrets.VERCEL_ORG_ID }}"
          
          echo "✅ Site redéployé avec les nouvelles configurations de protection"
          
      - name: Get Deployment URL
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          # Récupérer l'URL du déploiement
          DEPLOYMENT_URL=$(curl -s \
            "https://api.vercel.com/v9/projects/${{ secrets.VERCEL_PROJECT_ID }}/deployments?limit=1" \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            | jq -r '.deployments[0].url')
            
          echo "🌐 URL du déploiement: https://$DEPLOYMENT_URL"
          echo "🔗 URL principale: https://regis-yvette.vercel.app"
          
          # Tester l'accessibilité
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "https://regis-yvette.vercel.app")
          
          if [ "$STATUS_CODE" = "200" ]; then
            echo "✅ Site accessible publiquement!"
          elif [ "$STATUS_CODE" = "401" ]; then
            echo "⚠️ Site protégé (authentification requise)"
          else
            echo "❌ Status HTTP: $STATUS_CODE"
          fi